name: Test

on: workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Set up default Python
        uses: actions/setup-python@v5
      - name: Display Python version
        run: python -VV
      - name: Test with unittest
        run: python -m unittest discover -s src
